version: '3.8'

services:
  api:
    build: .
    container_name: checkmate-backend
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: checkmate-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: checkmate
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
